# Generated by Django 5.0 on 2023-12-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clothing_type',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
    ]
